name: Daily Auto Poster

on:
  schedule:
    # Har 6 ghante mein chalega (Din mein 4 baar)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Ye line allow karti hai ki tum button daba ke bhi chala sako

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Auto Poster
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python main.py
